
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Recursos_Humanos
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Empleados
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Empleados()
    {

        this.Licencias = new HashSet<Licencias>();

        this.Permisos = new HashSet<Permisos>();

        this.Salida_Empleados = new HashSet<Salida_Empleados>();

        this.Vacaiones = new HashSet<Vacaiones>();

    }


    public int Id { get; set; }
        [Required(ErrorMessage ="Campo Requerido")]
    public int Codigo_Empleado { get; set; }
        [Required(ErrorMessage = "Campo Requerido")]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "Campo Requerido")]
        public string Apellido { get; set; }
        [Required(ErrorMessage = "Campo Requerido")]
        public string Telefono { get; set; }
        [Required(ErrorMessage = "Campo Requerido")]
        public Nullable<int> Departamento { get; set; }
        [Required(ErrorMessage = "Campo Requerido")]
        public Nullable<int> Cargo { get; set; }
        [Required(ErrorMessage = "Campo Requerido")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Fecha_Ingreso { get; set; }
        [Required(ErrorMessage = "Campo Requerido")]
        public Nullable<decimal> Salario { get; set; }
        [Required(ErrorMessage = "Campo Requerido")]
        public Nullable<bool> Estatus { get; set; }



    public virtual Cargos Cargos { get; set; }

    public virtual Departamentos Departamentos { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Licencias> Licencias { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Permisos> Permisos { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Salida_Empleados> Salida_Empleados { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Vacaiones> Vacaiones { get; set; }

}

}
