
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Recursos_Humanos
{

using System;
    using System.Collections.Generic;
    
public partial class Licencias
{

    public int Id { get; set; }

    public Nullable<int> Empleado_id { get; set; }

    public Nullable<System.DateTime> Desde { get; set; }

    public Nullable<System.DateTime> Hasta { get; set; }

    public string Motivos { get; set; }

    public string Comentarios { get; set; }



    public virtual Empleados Empleados { get; set; }

}

}
