
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Recursos_Humanos
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Permisos
{

    public int Id { get; set; }
        [Required(ErrorMessage = "Campo Requerido")]
        public Nullable<int> Empleado_id { get; set; }
        [Required(ErrorMessage = "Campo Requerido")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Desde { get; set; }
        [Required(ErrorMessage = "Campo Requerido")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Hasta { get; set; }
        [Required(ErrorMessage = "Campo Requerido")]
        public string Comentarios { get; set; }



    public virtual Empleados Empleados { get; set; }

}

}
